from enum import StrEnum


class ErrorCode(StrEnum):
    AI_NOT_CONFIGURED = "AI_NOT_CONFIGURED"
    AI_NOT_ENABLED = "AI_NOT_ENABLED"
    AI_QUOTA_EXCEEDED = "AI_QUOTA_EXCEEDED"
    AI_UPSTREAM_TIMEOUT = "AI_UPSTREAM_TIMEOUT"
    AI_UPSTREAM_UNAVAILABLE = "AI_UPSTREAM_UNAVAILABLE"
    BUSINESS_CONFLICT = "BUSINESS_CONFLICT"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    HTTP_ERROR = "HTTP_ERROR"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
