"""create farm operations

Revision ID: 2c972e3fc98e
Revises: 093fa42fe3ad
Create Date: 2026-08-19 15:20:38.413647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c972e3fc98e'
down_revision: Union[str, Sequence[str], None] = '093fa42fe3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_operations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('plot_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('production_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('operation_type', sa.String(length=30), nullable=False),
    sa.Column('work_method', sa.String(length=20), nullable=False),
    sa.Column('operated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_farm_operations_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_farm_operations_operator_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], name=op.f('fk_farm_operations_plot_id_plots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_farm_operations_production_id_productions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_operations'))
    )
    op.create_index(op.f('ix_farm_operations_operator_id'), 'farm_operations', ['operator_id'], unique=False)
    op.create_index(op.f('ix_farm_operations_plot_id'), 'farm_operations', ['plot_id'], unique=False)
    op.create_index(op.f('ix_farm_operations_production_id'), 'farm_operations', ['production_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_operations_production_id'), table_name='farm_operations')
    op.drop_index(op.f('ix_farm_operations_plot_id'), table_name='farm_operations')
    op.drop_index(op.f('ix_farm_operations_operator_id'), table_name='farm_operations')
    op.drop_table('farm_operations')
    # ### end Alembic commands ###
