"""add production ended at

Revision ID: ebab87a2e453
Revises: e9a5f8d2b7c4
Create Date: 2026-08-31 15:46:01.964458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebab87a2e453'
down_revision: Union[str, Sequence[str], None] = 'e9a5f8d2b7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productions', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'ended_at')
    # ### end Alembic commands ###
